server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: http://localhost:8081
          predicates:
            - Path=/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG